name: PR Comment Bot
on:
  issue_comment:
    types: [created]

jobs:
  pr-comment:
    if : ${{ github.event.issue.pull_request}}
    runs-on: ubuntu-latest
    env:
      BOT_GH_TOKEN: ${{ secrets.SDK_GH_BOT1_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: sendbird/release-automation-action@latest
        with:
          gh_token: ${{ env.BOT_GH_TOKEN }}
          product: 'uikit'
          platform: 'js'
          framework: 'react'
          product_jira_project_key: 'UIKIT'
          product_jira_version_prefix: 'js_uikit'
          ci: 'github'
      