name: Release

on:
  pull_request:
    types: [closed, labeled]

jobs:
  build-release:
    # Only run the job if the PR has been merged and contains "release" label
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Start
        run: echo Building...